# 使用基础镜像
FROM python:3.9-slim

# 设置代理环境变量
# ENV HTTP_PROXY="http://172.16.5.104:7890"
# ENV HTTPS_PROXY="http://172.16.5.104:7890"

# 设置工作目录
WORKDIR /app

# 安装 Git 以便克隆仓库
RUN apt-get update && apt-get install -y git

# 克隆代码仓库
RUN git clone https://github.com/FunAudioLLM/SenseVoice.git .

# 将当前目录下的所有文件和子目录复制到容器的 /app 目录
COPY . /app/

# 安装依赖
RUN pip install -r requirements.txt

# 暴露端口
EXPOSE 8000

# 运行应用程序
CMD ["python", "app.py"]

