services:
  static-file-serve:
    image: eleven9809/static-file-serve:v0.1
    container_name: sfs
    volumes:
      - ./static:/opt
      - ./app.py:/app/app.py
    ports:
      - "6002:6002"
    command: [ "python", "/app/app.py" ]
