services:
  static-file-serve:
    image: eleven9809/static-file-serve:v0.1
    container_name: sfs
    volumes:
      - ../../app:/mnt/audio
    ports:
      - "6002:6002"
    entrypoint: tail
    command: [ "-f", "/dev/null" ]

