#services:
#  audio-separator:
#    image: eleven9809/as:cpu-v0.1
#    container_name: as-cpu
#    volumes:
#      - ./data:/tmp
#    entrypoint: tail
#    command: ["-f", "/dev/null"]

# gpu service
services:
  audio-separator:
    image: eleven9809/as:gpu-v0.1
    container_name: as-gpu
    volumes:
      - ./data:/tmp
    ports:
      - "6000:6000"
    entrypoint: tail
    command: ["-f", "/dev/null"]